site_name: LQG Docs
site_url: https://example.com/
repo_url: https://github.com/RothkopfLab/lqg
repo_name: RothkopfLab/lqg

nav:
  - Home: index.md
  # - Simple: simple.ipynb
  - TutorialTest: TutorialTest.ipynb
  - Altair: TutorialAltair.ipynb
  - Data: notebooks/Data.ipynb
  - Temp: temp.ipynb
  - About: about.md

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  logo: images/experimenter-actor-loop.png
  favicon: images/favicon.ico

  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue grey
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue grey
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/solid/scroll #solid/file-pdf
      link: https://elifesciences.org/articles/76635
      name: eLife Paper

plugins:
  - mkdocs-jupyter:
      execute: false
