site_name: "LQG: Inverse Optimal Control for Continuous Psychophysics"
site_url: https://example.com/  # TODO
repo_url: https://github.com/RothkopfLab/lqg
repo_name: RothkopfLab/lqg

nav:
  - Home: README.md
  - Tutorials:
    #- TutorialTest: TutorialTest.ipynb
    - Altair: TutorialAltair.ipynb
    - Data: notebooks/Data.ipynb
    - Simple: simple.ipynb
  - API: api.md
  - About: about.md

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  logo: images/experimenter-actor-loop.png
  favicon: images/favicon.ico
  
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - toc.follow
    - search.suggest

  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue grey
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue grey
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/solid/scroll #solid/file-pdf
      link: https://elifesciences.org/articles/76635
      name: eLife Paper

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - mkdocs-jupyter:
      execute: false
      ignore_h1_titles: True  # For now
